# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'LPPhotoViewer-swift-Sample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LPPhotoViewer-swift-Sample
  pod 'SDWebImage', '~> 3.8'
end
